<?php
/**
 * The library's section "cta-banner" as a block pattern, made for the site it is inserted on (generated by bin/build-block-library.php).
 *
 * @package DXAI_UI
 */

defined( 'ABSPATH' ) || exit;

echo \DXAI_UI\Pages\Block_Library::pattern( 'cta-banner' ); // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped
